<?php

use Illuminate\Database\Seeder;

class TradesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('trades')->insert([
            [
              'sneaker_id' => 1,
              'size' => 27.5,
              'price' => 30000,
              'trade_date' => '2019/07/20',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 2,
              'size' => 27,
              'price' => 32000,
              'trade_date' => '2019/07/24',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 2,
              'size' => 26,
              'price' => 31000,
              'trade_date' => '2019/07/29',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 2,
              'size' => 27,
              'price' => 34000,
              'trade_date' => '2019/08/03',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 4,
              'size' => 25.5,
              'price' => 28000,
              'trade_date' => '2019/08/03',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 2,
              'size' => 28,
              'price' => 33000,
              'trade_date' => '2019/08/05',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 7,
              'size' => 26.5,
              'price' => 38000,
              'trade_date' => '2019/08/11',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 8,
              'size' => 25,
              'price' => 23000,
              'trade_date' => '2019/08/13',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 1,
              'size' => 27,
              'price' => 28000,
              'trade_date' => '2019/08/13',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 4,
              'size' => 28.5,
              'price' => 27000,
              'trade_date' => '2019/08/15',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 2,
              'size' => 26.5,
              'price' => 40000,
              'trade_date' => '2019/08/18',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 9,
              'size' => 25.5,
              'price' => 29000,
              'trade_date' => '2019/08/22',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 4,
              'size' => 26,
              'price' => 25000,
              'trade_date' => '2019/08/29',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 4,
              'size' => 25.5,
              'price' => 30000,
              'trade_date' => '2019/09/01',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 6,
              'size' => 26.5,
              'price' => 31000,
              'trade_date' => '2019/09/04',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 3,
              'size' => 28,
              'price' => 34000,
              'trade_date' => '2019/09/07',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 7,
              'size' => 29.5,
              'price' => 29000,
              'trade_date' => '2019/09/10',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 2,
              'size' => 27,
              'price' => 31000,
              'trade_date' => '2019/09/11',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 1,
              'size' => 25.5,
              'price' => 35000,
              'trade_date' => '2019/09/13',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 7,
              'size' => 28,
              'price' => 31000,
              'trade_date' => '2019/09/15',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 2,
              'size' => 30,
              'price' => 32000,
              'trade_date' => '2019/09/17',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 4,
              'size' => 27.5,
              'price' => 29000,
              'trade_date' => '2019/09/18',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 2,
              'size' => 26.5,
              'price' => 42000,
              'trade_date' => '2019/09/19',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 8,
              'size' => 27.5,
              'price' => 33000,
              'trade_date' => '2019/09/21',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 7,
              'size' => 26,
              'price' => 34000,
              'trade_date' => '2019/09/26',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 1,
              'size' => 26.5,
              'price' => 30000,
              'trade_date' => '2019/09/27',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 2,
              'size' => 26,
              'price' => 45000,
              'trade_date' => '2019/09/27',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 5,
              'size' => 25,
              'price' => 30000,
              'trade_date' => '2019/09/28',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 6,
              'size' => 26.5,
              'price' => 37000,
              'trade_date' => '2019/09/30',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 6,
              'size' => 27.5,
              'price' => 31000,
              'trade_date' => '2019/10/02',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 5,
              'size' => 26,
              'price' => 34000,
              'trade_date' => '2019/10/03',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 2,
              'size' => 25.5,
              'price' => 44000,
              'trade_date' => '2019/10/05',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 3,
              'size' => 27.5,
              'price' => 30000,
              'trade_date' => '2019/10/07',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 2,
              'size' => 29.5,
              'price' => 38000,
              'trade_date' => '2019/10/09',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 3,
              'size' => 26.5,
              'price' => 39000,
              'trade_date' => '2019/10/10',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 7,
              'size' => 25.5,
              'price' => 30000,
              'trade_date' => '2019/10/10',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 1,
              'size' => 28.5,
              'price' => 29000,
              'trade_date' => '2019/10/11',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 7,
              'size' => 27,
              'price' => 33000,
              'trade_date' => '2019/10/12',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 8,
              'size' => 28,
              'price' => 36000,
              'trade_date' => '2019/10/12',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 5,
              'size' => 27,
              'price' => 33000,
              'trade_date' => '2019/10/12',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 2,
              'size' => 26,
              'price' => 51000,
              'trade_date' => '2019/10/14',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 1,
              'size' => 27.5,
              'price' => 38000,
              'trade_date' => '2019/10/14',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 6,
              'size' => 25.5,
              'price' => 32000,
              'trade_date' => '2019/10/15',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 3,
              'size' => 27.5,
              'price' => 41000,
              'trade_date' => '2019/10/16',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 7,
              'size' => 28.5,
              'price' => 39000,
              'trade_date' => '2019/10/16',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 2,
              'size' => 27,
              'price' => 54000,
              'trade_date' => '2019/10/18',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 9,
              'size' => 27.5,
              'price' => 30000,
              'trade_date' => '2019/10/18',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 4,
              'size' => 28.5,
              'price' => 29000,
              'trade_date' => '2019/10/18',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 2,
              'size' => 25.5,
              'price' => 47000,
              'trade_date' => '2019/10/19',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
            [
              'sneaker_id' => 8,
              'size' => 27.5,
              'price' => 42000,
              'trade_date' => '2019/10/19',
              'created_at' => new DateTime(),
              'updated_at' => new DateTime(),
            ],
          ]);
    }
}
