//
// Color.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Color: Codable {

    public var name: String

    public init(name: String) {
        self.name = name
    }


}

