//
// SizeInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct SizeInfo: Codable {

    public var size: Double
    public var lowestPrice: Int

    public init(size: Double, lowestPrice: Int) {
        self.size = size
        self.lowestPrice = lowestPrice
    }


}

