//
// SneakerAll.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct SneakerAll: Codable {

    public var _id: Int64
    public var num: Int
    public var popular: [SneakerRanking]
    public var lowest: [SneakerRanking]
    public var highest: [SneakerRanking]

    public init(_id: Int64, num: Int, popular: [SneakerRanking], lowest: [SneakerRanking], highest: [SneakerRanking]) {
        self._id = _id
        self.num = num
        self.popular = popular
        self.lowest = lowest
        self.highest = highest
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case num
        case popular
        case lowest
        case highest
    }


}

