//
// Sneaker.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Sneaker: Codable {

    public var _id: Int64
    public var nameMain: String
    public var nameSub: String
    public var image: String
    public var partNo: String
    public var colors: [Color]
    public var releaseDate: String
    public var regularPrice: Int

    public init(_id: Int64, nameMain: String, nameSub: String, image: String, partNo: String, colors: [Color], releaseDate: String, regularPrice: Int) {
        self._id = _id
        self.nameMain = nameMain
        self.nameSub = nameSub
        self.image = image
        self.partNo = partNo
        self.colors = colors
        self.releaseDate = releaseDate
        self.regularPrice = regularPrice
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case nameMain
        case nameSub
        case image
        case partNo
        case colors
        case releaseDate
        case regularPrice
    }


}

