//
// SneakerDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct SneakerDetail: Codable {

    public var _id: Int64
    public var nameMain: String
    public var nameSub: String
    public var image: String
    public var price: Int

    public init(_id: Int64, nameMain: String, nameSub: String, image: String, price: Int) {
        self._id = _id
        self.nameMain = nameMain
        self.nameSub = nameSub
        self.image = image
        self.price = price
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case nameMain
        case nameSub
        case image
        case price
    }


}

