//
// TradeHistroy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct TradeHistroy: Codable {

    public var _id: Int64
    public var tradeNum: Int
    public var trades: [TradeInfo]

    public init(_id: Int64, tradeNum: Int, trades: [TradeInfo]) {
        self._id = _id
        self.tradeNum = tradeNum
        self.trades = trades
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case tradeNum
        case trades
    }


}

