//
// TradeInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct TradeInfo: Codable {

    public var _id: Int64
    public var size: Double
    public var tradePrice: Int
    public var tradeDate: String

    public init(_id: Int64, size: Double, tradePrice: Int, tradeDate: String) {
        self._id = _id
        self.size = size
        self.tradePrice = tradePrice
        self.tradeDate = tradeDate
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case size
        case tradePrice
        case tradeDate
    }


}

