//
// TradeSize.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct TradeSize: Codable {

    public var _id: Int64
    public var sizes: [SizeInfo]

    public init(_id: Int64, sizes: [SizeInfo]) {
        self._id = _id
        self.sizes = sizes
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case sizes
    }


}

