//
// UserLogin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct UserLogin: Codable {

    public var mail: String
    public var password: String

    public init(mail: String, password: String) {
        self.mail = mail
        self.password = password
    }


}

