//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct User: Codable {

    public var firstName: String
    public var lastName: String
    public var firstNameKana: String
    public var lastNameKana: String
    public var mail: String
    public var password: String

    public init(firstName: String, lastName: String, firstNameKana: String, lastNameKana: String, mail: String, password: String) {
        self.firstName = firstName
        self.lastName = lastName
        self.firstNameKana = firstNameKana
        self.lastNameKana = lastNameKana
        self.mail = mail
        self.password = password
    }


}

