//
// ExhibitAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Alamofire



open class ExhibitAPI {
    /**
     Create Exhibit.
     
     - parameter modelError: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createExhibit(modelError: ModelError? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        createExhibitWithRequestBuilder(modelError: modelError).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Create Exhibit.
     - POST /exhibit[WIP]
     - parameter modelError: (body)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func createExhibitWithRequestBuilder(modelError: ModelError? = nil) -> RequestBuilder<Void> {
        let path = "/exhibit[WIP]"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: modelError)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Delete Exhibit by ID.
     
     - parameter exhibitId: (path) Exhibit Id. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteExhibit(exhibitId: Int64, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        deleteExhibitWithRequestBuilder(exhibitId: exhibitId).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Delete Exhibit by ID.
     - DELETE /exhibit/{exhibitId}
     - parameter exhibitId: (path) Exhibit Id. 
     - returns: RequestBuilder<Void> 
     */
    open class func deleteExhibitWithRequestBuilder(exhibitId: Int64) -> RequestBuilder<Void> {
        var path = "/exhibit/{exhibitId}"
        let exhibitIdPreEscape = "\(exhibitId)"
        let exhibitIdPostEscape = exhibitIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{exhibitId}", with: exhibitIdPostEscape, options: .literal, range: nil)
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = OpenAPIClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get Exhibit by ID.
     
     - parameter sneakerId: (path) Sneaker Id. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getExhibit(sneakerId: Int64, completion: @escaping ((_ data: ModelError?,_ error: Error?) -> Void)) {
        getExhibitWithRequestBuilder(sneakerId: sneakerId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get Exhibit by ID.
     - GET /exhibit/{sneakerId}[WIP]
     - parameter sneakerId: (path) Sneaker Id. 
     - returns: RequestBuilder<ModelError> 
     */
    open class func getExhibitWithRequestBuilder(sneakerId: Int64) -> RequestBuilder<ModelError> {
        var path = "/exhibit/{sneakerId}[WIP]"
        let sneakerIdPreEscape = "\(sneakerId)"
        let sneakerIdPostEscape = sneakerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{sneakerId}", with: sneakerIdPostEscape, options: .literal, range: nil)
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<ModelError>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
